<a href="https://colab.research.google.com/github/AleksTurov/Data-Science/blob/main/sql-ex/sqlex_postgres_in_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SQL-EX with Postgres

#Обучающий этап

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# Install postgresql server
!sudo apt-get -y -qq update
!sudo apt-get -y -qq install postgresql
!sudo service postgresql start

# Setup a password `postgres` for username `postgres`
!sudo -u postgres psql -U postgres -c "ALTER USER postgres PASSWORD 'postgres';"

debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 10.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Selecting previously unselected package cron.
(Reading database ... 122349 files and directories currently installed.)
Preparing to unpack .../0-cron_3.0pl1-136ubuntu1_amd64.deb ...
Unpacking cron (3.0pl1-136ubuntu1) ...
Selecting previously unselected package logrotate.
Preparing to unpack .../1-logrotate_3.14.0-4ubuntu3_amd64.deb ...
Unpacking logrotate (3.14.0-4ubuntu3) ...
Selecting previously unselected package netbase.
Preparing to unpack .../2-netbase_6.1_all.deb ...
Unpacking netbase (6.1) ...
Selecting previously unselected package pos

In [3]:
from sqlalchemy import create_engine
con = create_engine('postgresql+psycopg2://postgres:postgres@localhost:5432/postgres')

Скачиваем данные с sql-ex

In [4]:
!wget https://sql-ex.ru/download/sql-ex-pg.sql

--2023-04-10 06:15:57--  https://sql-ex.ru/download/sql-ex-pg.sql
Resolving sql-ex.ru (sql-ex.ru)... 5.188.73.5, 2a00:ab00:1203:22:ce0:a1ff:fee0:bb42
Connecting to sql-ex.ru (sql-ex.ru)|5.188.73.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 41053 (40K) [application/x-sql]
Saving to: ‘sql-ex-pg.sql’

sql-ex-pg.sql       100%[===================>]  40.09K  --.-KB/s    in 0s      

2023-04-10 06:15:58 (246 MB/s) - ‘sql-ex-pg.sql’ saved [41053/41053]



In [5]:
with open('/content/sql-ex-pg.sql', 'r') as file:
    sql = file.read()

Запускаем скрипт

In [6]:
con.execute(sql[1:])

<ipython-input-6-5ee16aa31c9c>:1: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  con.execute(sql[1:])


Сделаю еще свою знаменитую функцию select, которая заворачивает пандосовкую функцию. Нужно для того, чтобы каждый раз не писать всю эту авадакедавру, а писать красивенький селект

In [7]:
import pandas as pd
import numpy as np
import sqlite3

In [8]:
def select(sql):
  return pd.read_sql(sql,con)

## Задание: 1 (Serge I: 2002-09-30)

Схема БД состоит из четырех таблиц:  
Product(maker, model, type)  
PC(code, model, speed, ram, hd, cd, price)  
Laptop(code, model, speed, ram, hd, price, screen)  
Printer(code, model, color, type, price)  
  Таблица Product представляет производителя (maker), номер модели (model) и тип ('PC' - ПК, 'Laptop' - ПК-блокнот или 'Printer' - принтер). Предполагается, что номера моделей в таблице Product уникальны для всех производителей и типов продуктов.   
  В таблице PC для каждого ПК, однозначно определяемого уникальным кодом – code, указаны модель – model (внешний ключ к таблице Product), скорость - speed (процессора в мегагерцах), объем памяти - ram (в мегабайтах), размер диска - hd (в гигабайтах), скорость считывающего устройства - cd (например, '4x') и цена - price (в долларах).   
  Таблица Laptop аналогична таблице РС за исключением того, что вместо скорости CD содержит размер экрана -screen (в дюймах).   
В таблице Printer для каждой модели принтера указывается, является ли он цветным - color ('y', если цветной), тип принтера - type (лазерный – 'Laser', струйный – 'Jet' или матричный – 'Matrix') и цена - price.

Найдите номер модели, скорость и размер жесткого диска для всех ПК стоимостью менее 500 дол. Вывести: model, speed и hd

### Анализ данных

In [9]:
sql = '''select * from PC t'''

In [10]:
select(sql)

code model  speed  ram    hd   cd  price
0      1  1232    500   64   5.0  12x  600.0
1      2  1121    750  128  14.0  40x  850.0
2      3  1233    500   64   5.0  12x  600.0
3      4  1121    600  128  14.0  40x  850.0
4      5  1121    600  128   8.0  40x  850.0
5      6  1233    750  128  20.0  50x  950.0
6      7  1232    500   32  10.0  12x  400.0
7      8  1232    450   64   8.0  24x  350.0
8      9  1232    450   32  10.0  24x  350.0
9     10  1260    500   32  10.0  12x  350.0
10    11  1233    900  128  40.0  40x  980.0
11    12  1233    800  128  20.0  50x  970.0

### Как это сделать в pandas

> Indented block



In [11]:
df = select(sql)

In [12]:
price_500 = df.query('price < 500')#отсортируем значение цены меньше 500

In [13]:
price_500 = price_500.drop(['code','ram', 'cd','price'], axis=1)# удалим лишнии столбцы и получим наш результат

In [14]:
price_500#Можно загружать в базу данных без индексов

model  speed    hd
6  1232    500  10.0
7  1232    450   8.0
8  1232    450  10.0
9  1260    500  10.0

### Как это сделать в sql

In [15]:
select(sql)

code model  speed  ram    hd   cd  price
0      1  1232    500   64   5.0  12x  600.0
1      2  1121    750  128  14.0  40x  850.0
2      3  1233    500   64   5.0  12x  600.0
3      4  1121    600  128  14.0  40x  850.0
4      5  1121    600  128   8.0  40x  850.0
5      6  1233    750  128  20.0  50x  950.0
6      7  1232    500   32  10.0  12x  400.0
7      8  1232    450   64   8.0  24x  350.0
8      9  1232    450   32  10.0  24x  350.0
9     10  1260    500   32  10.0  12x  350.0
10    11  1233    900  128  40.0  40x  980.0
11    12  1233    800  128  20.0  50x  970.0

In [16]:
sql = '''Select t.model, t.speed, t.hd from PC t
where t.price < 500'''

In [17]:
select(sql)

model  speed    hd
0  1232    500  10.0
1  1232    450   8.0
2  1232    450  10.0
3  1260    500  10.0

## Задание: 2 (Serge I: 2002-09-21)

Найдите производителей принтеров. Вывести: maker

### Как это сделать в pandas

In [18]:
sql = '''select * from Product t'''

In [19]:
df = select(sql)

In [20]:
df

maker model     type
0      B  1121       PC
1      A  1232       PC
2      A  1233       PC
3      E  1260       PC
4      A  1276  Printer
5      D  1288  Printer
6      A  1298   Laptop
7      C  1321   Laptop
8      A  1401  Printer
9      A  1408  Printer
10     D  1433  Printer
11     E  1434  Printer
12     B  1750   Laptop
13     A  1752   Laptop
14     E  2113       PC
15     E  2112       PC

In [21]:
df[df['type'] == 'Printer'].groupby('maker')['type'].count()#Все модели принтеров и даже с количеством

maker
A    3
D    2
E    1
Name: type, dtype: int64

### Как это сделать в sql

In [22]:
sql = '''select t.maker
from Product t 
where t.type = 'Printer'
group by t.maker'''

In [23]:
select(sql)

maker
0     A
1     D
2     E

## Задание: 3 (Serge I: 2002-09-30)



Найдите номер модели, объем памяти и размеры экранов ПК-блокнотов, цена которых превышает 1000 дол.

### Как это сделать в pandas



In [24]:
sql = '''select * from laptop t'''

In [25]:
df = select(sql)

Сначала глянем на таблу с ПК-блокнотами, ну т.е. ноутбуками



In [26]:
df

code model  speed  ram    hd   price  screen
0     1  1298    350   32   4.0   700.0      11
1     2  1321    500   64   8.0   970.0      12
2     3  1750    750  128  12.0  1200.0      14
3     4  1298    600   64  10.0  1050.0      15
4     5  1752    750  128  10.0  1150.0      14
5     6  1298    450   64  10.0   950.0      12

In [27]:
df.query('price>1000').drop(['code','speed', 'hd','price'], axis=1)

model  ram  screen
2  1750  128      14
3  1298   64      15
4  1752  128      14

### Как это сделать в sql

Сначала глянем на таблу с ПК-блокнотами, ну т.е. ноутбуками



In [28]:
sql = '''select * from laptop t'''

In [29]:
select(sql)

code model  speed  ram    hd   price  screen
0     1  1298    350   32   4.0   700.0      11
1     2  1321    500   64   8.0   970.0      12
2     3  1750    750  128  12.0  1200.0      14
3     4  1298    600   64  10.0  1050.0      15
4     5  1752    750  128  10.0  1150.0      14
5     6  1298    450   64  10.0   950.0      12

Теперь напишем сам запрос

In [30]:
sql = '''
select t.model, t.ram, t.screen from laptop t
where t.price > 1000
'''

In [31]:
select(sql)

model  ram  screen
0  1750  128      14
1  1298   64      15
2  1752  128      14

## Задание: 4 (Serge I: 2002-09-21)


Найдите все записи таблицы Printer для цветных принтеров.


### Как это сделать в pandas



In [32]:
sql = '''select * from Printer t'''

In [33]:
df = select(sql)
df


code model color    type  price
0     1  1276     n   Laser  400.0
1     2  1433     y     Jet  270.0
2     3  1434     y     Jet  290.0
3     4  1401     n  Matrix  150.0
4     5  1408     n  Matrix  270.0
5     6  1288     n   Laser  400.0

In [34]:
df[df['color'] == 'y']

code model color type  price
1     2  1433     y  Jet  270.0
2     3  1434     y  Jet  290.0

### Как это сделать в sql

In [35]:
select(sql)

code model color    type  price
0     1  1276     n   Laser  400.0
1     2  1433     y     Jet  270.0
2     3  1434     y     Jet  290.0
3     4  1401     n  Matrix  150.0
4     5  1408     n  Matrix  270.0
5     6  1288     n   Laser  400.0

In [36]:
sql = '''
select * from Printer t
where (t.color like 'y')
'''

In [37]:
select(sql)

code model color type  price
0     2  1433     y  Jet  270.0
1     3  1434     y  Jet  290.0

## Задание: 5 (Serge I: 2002-09-30)

Найдите номер модели, скорость и размер жесткого диска ПК, имеющих 12x или 24x CD и цену менее 600 дол

### Как это сделать в pandas


In [38]:
sql = '''select * from PC t'''
df = select(sql)
df

code model  speed  ram    hd   cd  price
0      1  1232    500   64   5.0  12x  600.0
1      2  1121    750  128  14.0  40x  850.0
2      3  1233    500   64   5.0  12x  600.0
3      4  1121    600  128  14.0  40x  850.0
4      5  1121    600  128   8.0  40x  850.0
5      6  1233    750  128  20.0  50x  950.0
6      7  1232    500   32  10.0  12x  400.0
7      8  1232    450   64   8.0  24x  350.0
8      9  1232    450   32  10.0  24x  350.0
9     10  1260    500   32  10.0  12x  350.0
10    11  1233    900  128  40.0  40x  980.0
11    12  1233    800  128  20.0  50x  970.0

In [39]:
df.query(("cd == '12x'" or "cd == '24x'") and "price<600").drop(['code','ram','cd', 'price'], axis=1)

model  speed    hd
6  1232    500  10.0
7  1232    450   8.0
8  1232    450  10.0
9  1260    500  10.0

### Как это сделать в sql




In [40]:
select(sql)

code model  speed  ram    hd   cd  price
0      1  1232    500   64   5.0  12x  600.0
1      2  1121    750  128  14.0  40x  850.0
2      3  1233    500   64   5.0  12x  600.0
3      4  1121    600  128  14.0  40x  850.0
4      5  1121    600  128   8.0  40x  850.0
5      6  1233    750  128  20.0  50x  950.0
6      7  1232    500   32  10.0  12x  400.0
7      8  1232    450   64   8.0  24x  350.0
8      9  1232    450   32  10.0  24x  350.0
9     10  1260    500   32  10.0  12x  350.0
10    11  1233    900  128  40.0  40x  980.0
11    12  1233    800  128  20.0  50x  970.0

In [41]:
sql = '''
select t.model, t.speed, t.hd from PC t
where ((t.cd like '12x' or t.cd like '24x') 
and t.price < 600)
'''

In [42]:
select(sql)

model  speed    hd
0  1232    500  10.0
1  1232    450   8.0
2  1232    450  10.0
3  1260    500  10.0

## Задание: 6 (Serge I: 2002-10-28)

Для каждого производителя, выпускающего ПК-блокноты c объёмом жесткого диска не менее 10 Гбайт, найти скорости таких ПК-блокнотов. Вывод: производитель, скорость.


### Как это сделать в pandas


In [43]:
sql = '''select * from Laptop t'''
df = select(sql)
df

code model  speed  ram    hd   price  screen
0     1  1298    350   32   4.0   700.0      11
1     2  1321    500   64   8.0   970.0      12
2     3  1750    750  128  12.0  1200.0      14
3     4  1298    600   64  10.0  1050.0      15
4     5  1752    750  128  10.0  1150.0      14
5     6  1298    450   64  10.0   950.0      12

In [44]:
sql = '''select * from Product t'''
df2 = select(sql)
df2

maker model     type
0      B  1121       PC
1      A  1232       PC
2      A  1233       PC
3      E  1260       PC
4      A  1276  Printer
5      D  1288  Printer
6      A  1298   Laptop
7      C  1321   Laptop
8      A  1401  Printer
9      A  1408  Printer
10     D  1433  Printer
11     E  1434  Printer
12     B  1750   Laptop
13     A  1752   Laptop
14     E  2113       PC
15     E  2112       PC

In [45]:
data = df.set_index('model').join(df2.set_index('model'))

In [46]:
data

code  speed  ram    hd   price  screen maker    type
model                                                      
1298      1    350   32   4.0   700.0      11     A  Laptop
1298      4    600   64  10.0  1050.0      15     A  Laptop
1298      6    450   64  10.0   950.0      12     A  Laptop
1321      2    500   64   8.0   970.0      12     C  Laptop
1750      3    750  128  12.0  1200.0      14     B  Laptop
1752      5    750  128  10.0  1150.0      14     A  Laptop

In [47]:
data = data.query("hd >=10").drop(['code','ram', 'hd', 'price', 'screen', 'type'], axis=1)
data

speed maker
model             
1298     600     A
1298     450     A
1750     750     B
1752     750     A

### Как это сделать в sql

In [48]:
sql = '''select * from Laptop t'''
select(sql)

code model  speed  ram    hd   price  screen
0     1  1298    350   32   4.0   700.0      11
1     2  1321    500   64   8.0   970.0      12
2     3  1750    750  128  12.0  1200.0      14
3     4  1298    600   64  10.0  1050.0      15
4     5  1752    750  128  10.0  1150.0      14
5     6  1298    450   64  10.0   950.0      12

In [49]:
sql = '''select * from Laptop t
left join Product i on t.model = i.model

'''

In [50]:
select(sql)

code model  speed  ram    hd   price  screen maker model    type
0     1  1298    350   32   4.0   700.0      11     A  1298  Laptop
1     2  1321    500   64   8.0   970.0      12     C  1321  Laptop
2     3  1750    750  128  12.0  1200.0      14     B  1750  Laptop
3     4  1298    600   64  10.0  1050.0      15     A  1298  Laptop
4     5  1752    750  128  10.0  1150.0      14     A  1752  Laptop
5     6  1298    450   64  10.0   950.0      12     A  1298  Laptop

In [51]:
sql = '''select distinct t.maker, i.speed
from Product t
join Laptop i on t.model = i.model
where (t.type = 'Laptop' and i.hd >= 10)
'''

In [52]:
select(sql)

maker  speed
0     A    450
1     A    600
2     A    750
3     B    750

## Задание: 7 (Serge I: 2002-11-02)

Найдите номера моделей и цены всех имеющихся в продаже продуктов (любого типа) производителя B (латинская буква).

### Как это сделать в pandas


In [53]:
sql = '''select * from Laptop t'''
df = select(sql)


In [54]:
sql = '''select * from PC t'''
df1 = select(sql)

In [55]:
sql = '''select * from Printer t'''
df2 = select(sql)

In [56]:
frames = [df, df1, df2]

result = pd.concat(frames).drop(['code','speed', 'ram', 'hd', 'screen', 'cd', 'color', 'type'], axis=1)

In [57]:
result.head()

model   price
0  1298   700.0
1  1321   970.0
2  1750  1200.0
3  1298  1050.0
4  1752  1150.0

In [58]:

sql = '''select * from Product t'''
df3 = select(sql)

In [59]:
data = result.set_index('model').join(df3.set_index('model')).drop_duplicates()
data = data.query("maker == 'B'").drop(['type', 'maker'], axis=1)
data

price
model        
1121    850.0
1750   1200.0

### Как это сделать в sql

In [60]:
sql = '''select * from (select model, price 
from PC
union
select model, price 
from Laptop
union
select model, price 
from Printer
) as a
where a.model in (select model 
from Product 
where maker = 'B'
)'''

In [61]:
select(sql)

model   price
0  1121   850.0
1  1750  1200.0

## Задание: 8 (Serge I: 2003-02-03)

Найдите производителя, выпускающего ПК, но не ПК-блокноты.

### Как это сделать в pandas


Найдите производителя, выпускающего ПК, но не ПК-блокноты.

In [62]:
frames = [df, df1, df2]

result = pd.concat(frames)
result = pd.merge(result, df3, how="left", on=["model"])
result.head()#полная таблица

code model  speed    ram    hd   price  screen   cd color type_x maker  \
0     1  1298  350.0   32.0   4.0   700.0    11.0  NaN   NaN    NaN     A   
1     2  1321  500.0   64.0   8.0   970.0    12.0  NaN   NaN    NaN     C   
2     3  1750  750.0  128.0  12.0  1200.0    14.0  NaN   NaN    NaN     B   
3     4  1298  600.0   64.0  10.0  1050.0    15.0  NaN   NaN    NaN     A   
4     5  1752  750.0  128.0  10.0  1150.0    14.0  NaN   NaN    NaN     A   

   type_y  
0  Laptop  
1  Laptop  
2  Laptop  
3  Laptop  
4  Laptop

In [63]:
result1 = (result.query("type_y == 'PC'"))['maker'].unique()
result1

array(['A', 'B', 'E'], dtype=object)

In [64]:
result2 = (result.query("type_y == 'Laptop'"))['maker'].unique()
result2 

array(['A', 'C', 'B'], dtype=object)

### Как это сделать в sql

In [65]:
sql = '''select t.maker 
from Product t
where (t.type = 'PC')
EXCEPT
select t.maker
from Product t
where t.type = 'Laptop'
'''

In [66]:
select(sql)

maker
0     E

##Задание: 9 (Serge I: 2002-11-02)

Найдите производителей ПК с процессором не менее 450 Мгц. Вывести: Maker

### Как это сделать в pandas


In [67]:
res_9 = result.query("type_y == 'PC' and speed >= 450").drop_duplicates()
res_9['maker'].unique()

array(['A', 'B', 'E'], dtype=object)

### Как это сделать в sql

In [68]:
sql = '''select distinct t.maker
from Product t
join PC i on t.model = i.model
where (t.type = 'PC' and i.speed >= 450)
'''

In [69]:

select(sql)

maker
0     A
1     B
2     E

## Exercise: 10 (Serge I: 2002-09-23)

Найдите модели принтеров с самой высокой ценой. Набор результатов: модель, цена.


### Как это сделать в pandas


In [70]:
res_10 = result.query("type_y == 'Printer'")

In [71]:
res_10 = res_10.sort_values(by='price', ascending=False).head(2)

In [72]:
res_10 = res_10.drop(['code','speed', 'ram', 'hd', 'screen', 'cd', 'color', 'type_x', 'maker', 'type_y'], axis=1)
res_10

model  price
18  1276  400.0
23  1288  400.0

### Как это сделать в sql

In [73]:
sql = '''select model, price
from Printer
where price = (select max(price)
from Printer)
'''

In [74]:
select(sql)

model  price
0  1276  400.0
1  1288  400.0

## Exercise: 11 (Serge I: 2002-11-02)

Найдите среднюю скорость ПК.

### Как это сделать в pandas


In [75]:
res_11 = result.query("type_y == 'PC'")

In [76]:
res_11['speed'].mean()

608.3333333333334

### Как это сделать в sql

In [77]:
sql = '''select avg(speed)
from PC
'''

In [78]:
select(sql)

avg
0  608.333333

## Задание: 12 (Serge I: 2002-11-02)

Найдите среднюю скорость ПК-блокнотов, цена которых превышает 1000 дол.

### Как это сделать в pandas


In [79]:
res_12 = result.query("type_y == 'Laptop' and price> 1000")

In [80]:
res_12['speed'].mean()

700.0

### Как это сделать в sql

In [81]:
sql = '''select avg(speed)
from Laptop
where price > 1000
'''

In [82]:
select(sql)

avg
0  700.0

## Задание: 13 (Serge I: 2002-11-02)

Найдите среднюю скорость ПК, выпущенных производителем A.


### Как это сделать в pandas


In [83]:
res_13 = result.query("type_y == 'PC' and maker == 'A'")

In [84]:
res_13['speed'].mean()

606.25

### Как это сделать в sql

In [85]:
sql = '''select distinct avg(speed)
from Product t
join PC i on t.model = i.model
where (t.maker = 'A')
'''

In [86]:
select(sql)

avg
0  606.25

## Задание: 14 (Serge I: 2002-11-05)

Найдите класс, имя и страну для кораблей из таблицы Ships, имеющих не менее 10 орудий.

### Как это сделать в pandas


In [87]:
sql = '''select * 
from Classes
'''

In [88]:
df = select(sql)

In [89]:
df

class type     country  numguns  bore  displacement
0        Bismarck   bb     Germany        8  15.0         42000
1            Iowa   bb         USA        9  16.0         46000
2           Kongo   bc       Japan        8  14.0         32000
3  North Carolina   bb         USA       12  16.0         37000
4          Renown   bc  Gt.Britain        6  15.0         32000
5         Revenge   bb  Gt.Britain        8  15.0         29000
6       Tennessee   bb         USA       12  14.0         32000
7          Yamato   bb       Japan        9  18.0         65000

In [90]:
sql = '''select * 
from Ships
'''

In [91]:
df2 = select(sql)
df2

name           class  launched
0        California       Tennessee      1921
1            Haruna           Kongo      1916
2              Hiei           Kongo      1914
3              Iowa            Iowa      1943
4         Kirishima           Kongo      1915
5             Kongo           Kongo      1913
6          Missouri            Iowa      1944
7           Musashi          Yamato      1942
8        New Jersey            Iowa      1943
9    North Carolina  North Carolina      1941
10        Ramillies         Revenge      1917
11           Renown          Renown      1916
12          Repulse          Renown      1916
13       Resolution          Renown      1916
14          Revenge         Revenge      1916
15        Royal Oak         Revenge      1916
16  Royal Sovereign         Revenge      1916
17        Tennessee       Tennessee      1920
18       Washington  North Carolina      1941
19        Wisconsin            Iowa      1944
20           Yamato          Yamato      1941
21     South Dakota  North Carolina      1941

In [92]:
full_ship = pd.merge(df, df2, how="left", on=["class"])
full_ship.head()#полная таблица

class type  country  numguns  bore  displacement        name  launched
0  Bismarck   bb  Germany        8  15.0         42000         NaN       NaN
1      Iowa   bb      USA        9  16.0         46000        Iowa    1943.0
2      Iowa   bb      USA        9  16.0         46000    Missouri    1944.0
3      Iowa   bb      USA        9  16.0         46000  New Jersey    1943.0
4      Iowa   bb      USA        9  16.0         46000   Wisconsin    1944.0

In [93]:
full_ship.query("numguns >= 10")

class type country  numguns  bore  displacement            name  \
9   North Carolina   bb     USA       12  16.0         37000  North Carolina   
10  North Carolina   bb     USA       12  16.0         37000      Washington   
11  North Carolina   bb     USA       12  16.0         37000    South Dakota   
19       Tennessee   bb     USA       12  14.0         32000      California   
20       Tennessee   bb     USA       12  14.0         32000       Tennessee   

    launched  
9     1941.0  
10    1941.0  
11    1941.0  
19    1921.0  
20    1920.0

### Как это сделать в sql

In [94]:
sql = '''select t.class, t.name, i.country
from Ships t
left join Classes i on t.class = i.class
where i.numguns >=10
'''

In [95]:
select(sql)

class            name country
0       Tennessee      California     USA
1  North Carolina  North Carolina     USA
2       Tennessee       Tennessee     USA
3  North Carolina      Washington     USA
4  North Carolina    South Dakota     USA

##Задание: 15 (Serge I: 2003-02-03)

Найдите размеры жестких дисков, совпадающих у двух и более PC. Вывести: HD

### Как это сделать в pandas


In [96]:
res_15 = result.query("type_y == 'PC'")
res_15

code model  speed    ram    hd  price  screen   cd color type_x maker  \
6      1  1232  500.0   64.0   5.0  600.0     NaN  12x   NaN    NaN     A   
7      2  1121  750.0  128.0  14.0  850.0     NaN  40x   NaN    NaN     B   
8      3  1233  500.0   64.0   5.0  600.0     NaN  12x   NaN    NaN     A   
9      4  1121  600.0  128.0  14.0  850.0     NaN  40x   NaN    NaN     B   
10     5  1121  600.0  128.0   8.0  850.0     NaN  40x   NaN    NaN     B   
11     6  1233  750.0  128.0  20.0  950.0     NaN  50x   NaN    NaN     A   
12     7  1232  500.0   32.0  10.0  400.0     NaN  12x   NaN    NaN     A   
13     8  1232  450.0   64.0   8.0  350.0     NaN  24x   NaN    NaN     A   
14     9  1232  450.0   32.0  10.0  350.0     NaN  24x   NaN    NaN     A   
15    10  1260  500.0   32.0  10.0  350.0     NaN  12x   NaN    NaN     E   
16    11  1233  900.0  128.0  40.0  980.0     NaN  40x   NaN    NaN     A   
17    12  1233  800.0  128.0  20.0  970.0     NaN  50x   NaN    NaN     A   

   type_y  
6      PC  
7      PC  
8      PC  
9      PC  
10     PC  
11     PC  
12     PC  
13     PC  
14     PC  
15     PC  
16     PC  
17     PC

In [97]:
res_15.groupby(by='hd',  axis=0, as_index=True, sort=True)['price'].count()

hd
5.0     2
8.0     2
10.0    3
14.0    2
20.0    2
40.0    1
Name: price, dtype: int64

### Как это сделать в sql

In [98]:
sql = '''select t.hd as hd
from PC t
group by t.hd
having count(*) > 1

 '''

In [99]:
select(sql)

hd
0   8.0
1  20.0
2   5.0
3  14.0
4  10.0

## Задание: 16 (Serge I: 2003-02-03)

Найдите пары моделей PC, имеющих одинаковые скорость и RAM. В результате каждая пара указывается только один раз, т.е. (i,j), но не (j,i), Порядок вывода: модель с большим номером, модель с меньшим номером, скорость и RAM.

### Как это сделать в sql

In [100]:
sql = '''SELECT DISTINCT p1.model, p2.model, p1.speed, p1.ram
FROM PC p1, PC p2
WHERE p1.model > p2.model AND p1.speed = p2.speed AND p1.ram = p2.ram
ORDER BY p1.model DESC, p2.model ASC
 '''

In [101]:
select(sql)

model model  speed  ram
0  1260  1232    500   32
1  1233  1121    750  128
2  1233  1232    500   64

## Задание: 17 (Serge I: 2003-02-03)

Найдите модели ПК-блокнотов, скорость которых меньше скорости каждого из ПК.
Вывести: type, model, speed


### Как это сделать в pandas


In [102]:
min(result.query("type_y == 'PC'")['speed'])

450.0

In [103]:
result.query("type_y == 'Laptop' and speed<450")

code model  speed   ram   hd  price  screen   cd color type_x maker  type_y
0     1  1298  350.0  32.0  4.0  700.0    11.0  NaN   NaN    NaN     A  Laptop

### Как это сделать в sql

In [104]:
sql = '''select distinct i.type, t.model, t.speed
from Laptop t
left join Product i on t.model = i.model
where t.speed<ALL (select z.speed
from PC z)
'''

In [105]:
select(sql)

type model  speed
0  Laptop  1298    350

##Задание: 18 (Serge I: 2003-02-03)

Найдите производителей самых дешевых цветных принтеров. Вывести: maker, price

### Как это сделать в pandas


In [106]:
result.query("type_y == 'Printer' and color=='y'")

code model  speed  ram  hd  price  screen   cd color type_x maker   type_y
19     2  1433    NaN  NaN NaN  270.0     NaN  NaN     y    Jet     D  Printer
20     3  1434    NaN  NaN NaN  290.0     NaN  NaN     y    Jet     E  Printer

### Как это сделать в sql

In [107]:
sql = '''select distinct i.maker, t.price
from Printer t
left join Product i on t.model = i.model
where t.color = 'y' and 
t.price<=(select min(price) from Printer t where t.color = 'y')
'''

In [108]:

select(sql)

maker  price
0     D  270.0

## Задание: 19 (Serge I: 2003-02-13)

Для каждого производителя, имеющего модели в таблице Laptop, найдите средний размер экрана выпускаемых им ПК-блокнотов.
Вывести: maker, средний размер экрана.

In [109]:
sql = '''select maker, AVG(screen) from  Laptop l
left join Product p on l.model = p.model
group by p.maker
'''

In [110]:
select(sql)

maker   avg
0     B  14.0
1     C  12.0
2     A  13.0

## Задание: 20 (Serge I: 2003-02-13)


Найдите производителей, выпускающих по меньшей мере три различных модели ПК. Вывести: Maker, число моделей ПК.

In [111]:
sql = '''select * from  PC as pc
join Product p on p.model = pc.model
'''

In [112]:
select(sql)

code model  speed  ram    hd   cd  price maker model type
0      1  1232    500   64   5.0  12x  600.0     A  1232   PC
1      2  1121    750  128  14.0  40x  850.0     B  1121   PC
2      3  1233    500   64   5.0  12x  600.0     A  1233   PC
3      4  1121    600  128  14.0  40x  850.0     B  1121   PC
4      5  1121    600  128   8.0  40x  850.0     B  1121   PC
5      6  1233    750  128  20.0  50x  950.0     A  1233   PC
6      7  1232    500   32  10.0  12x  400.0     A  1232   PC
7      8  1232    450   64   8.0  24x  350.0     A  1232   PC
8      9  1232    450   32  10.0  24x  350.0     A  1232   PC
9     10  1260    500   32  10.0  12x  350.0     E  1260   PC
10    11  1233    900  128  40.0  40x  980.0     A  1233   PC
11    12  1233    800  128  20.0  50x  970.0     A  1233   PC

## Задание: 21 (Serge I: 2003-02-13)


Найдите максимальную цену ПК, выпускаемых каждым производителем, у которого есть модели в таблице PC.
Вывести: maker, максимальная цена.

In [113]:
sql = '''select p.maker, max(pc.price) from  PC as pc
left join Product p on pc.model = p.model
group by p.maker
'''

In [114]:
select(sql)

maker    max
0     B  850.0
1     E  350.0
2     A  980.0

## Задание: 22 (Serge I: 2003-02-13)


Для каждого значения скорости ПК, превышающего 600 МГц, определите среднюю цену ПК с такой же скоростью. Вывести: speed, средняя цена.

In [115]:
sql = '''select pc.speed, avg(pc.price) from  PC as pc
left join Product p on pc.model = p.model
where pc.speed > 600
group by pc.speed
'''

In [116]:
select(sql)

speed    avg
0    900  980.0
1    750  900.0
2    800  970.0

## Задание: 23 (Serge I: 2003-02-14)


Найдите производителей, которые производили бы как ПК
со скоростью не менее 750 МГц, так и ПК-блокноты со скоростью не менее 750 МГц.
Вывести: Maker

In [117]:
sql = '''select DISTINCT p.maker from  PC as pc
left join Product p on pc.model = p.model
where pc.speed >= 750 and
p.maker in (select DISTINCT p.maker from  Laptop as l
left join Product p on l.model = p.model
where l.speed >= 750)
'''

In [118]:
select(sql)

maker
0     B
1     A

## Задание: 24 (Serge I: 2003-02-03)


\Перечислите номера моделей любых типов, имеющих самую высокую цену по всей имеющейся в базе данных продукции.


In [119]:
sql = '''SELECT model, price 
FROM
(
  SELECT model, price FROM PC 
  UNION 
  SELECT model, price FROM Laptop 
  UNION 
  SELECT model, price FROM Printer
) AS all_pr
where all_pr.price = (SELECT max(price)
FROM
(
  SELECT model, price FROM PC 
  UNION 
  SELECT model, price FROM Laptop 
  UNION 
  SELECT model, price FROM Printer
) AS max_pr)
'''

In [120]:
select(sql)


model   price
0  1750  1200.0

## Задание: 25 (Serge I: 2003-02-14)



Найдите производителей принтеров, которые производят ПК с наименьшим объемом RAM и с самым быстрым процессором среди всех ПК, имеющих наименьший объем RAM. Вывести: Maker


In [121]:
sql = '''SELECT DISTINCT maker
FROM Product
WHERE type = 'Printer' AND maker IN (
  SELECT DISTINCT p1.maker
  FROM Product p1
  JOIN PC ON p1.model = PC.model AND PC.ram = (
    SELECT MIN(ram)
    FROM PC
  )
  WHERE p1.maker IN (
    SELECT DISTINCT p2.maker
    FROM Product p2
    JOIN PC ON p2.model = PC.model AND PC.ram = (
      SELECT MIN(ram)
      FROM PC
    )
    WHERE p2.type = 'PC'
  )
  AND PC.speed = (
    SELECT MAX(speed)
    FROM PC
    WHERE ram = (
      SELECT MIN(ram)
      FROM PC
    )
  )
)


'''

In [122]:
select(sql)


maker
0     A
1     E

#Рейтинговый этап

##Задание: 1 ($erges: 2008-06-21)

Дима и Миша пользуются продуктами от одного и того же производителя.
Тип Таниного принтера не такой, как у Вити, но признак "цветной или нет" - совпадает.  
Размер экрана Диминого ноутбука на 3 дюйма больше Олиного.
Мишин ПК в 4 раза дороже Таниного принтера.  
Номера моделей Витиного принтера и Олиного ноутбука отличаются только третьим символом.  
У Костиного ПК скорость процессора, как у Мишиного ПК; объем жесткого диска, как у Диминого ноутбука; объем памяти, как у Олиного ноутбука, а цена - как у Витиного принтера.  
Вывести все возможные номера моделей Костиного ПК.  


### Как это сделать в pandas
